service: stage
runtime: python27
threadsafe: true
skip_files:
  - ^(?!dist)
  - ^node_modules$
  - ^README\..*
  - \.gitignore
  - ^\.git$
  - ^grunt\.js
  - ^src$
  - ^e2e$
  - \.editorconfig
  - ^karma\.config\.js
  - ^package\.json
  - ^protractor\.conf\.js
  - ^tslint\.json
handlers:
  # Routing for bundles to serve directly
  - url: /((?:runtime|main|polyfills|styles|vendor)\.[a-z0-9]+\.js)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/cli/\1
    upload: dist/cli/.*

  # Routing for bundle maps to serve directly
  - url: /((?:runtime|main|polyfills|styles|vendor)\.[a-z0-9]+\.js\.map)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/cli/\1
    upload: dist/cli/.*

  # Routing for a prod styles.bundle.css to serve directly
  - url: /(styles\.[a-z0-9]+\.css)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/cli/\1
    upload: dist/cli/.*

  # Routing for typedoc, assets, and favicon.ico to serve directly
  - url: /((?:assets|docs)/.*|favicon\.ico)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/cli/\1
    upload: dist/cli/.*

  # Routing for service worker files serve directly
  - url: /(manifest\.json|ngsw\.json|ngsw-worker\.js|safety-worker\.js|worker-basic\.min\.js|ngsw_worker\.es6\.js\.map)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/cli/\1
    upload: dist/cli/.*
    # Any other requests are routed to index.html for angular to handle so we don't need hash URLs
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: dist/cli/index.html
    upload: dist/cli/index\.html
    http_headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains
      X-Frame-Options: DENY